# Build State
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS builder

WORKDIR /src
COPY src/ .

RUN dotnet restore && dotnet publish

# Final Image State
FROM mcr.microsoft.com/dotnet/sdk:5.0

WORKDIR /dotnetapp
COPY --from=builder /src/bin/Debug/net5.0/publish .

CMD ["dotnet", "my-app.dll"]